name: Pull and Push Code

on:
  push:
    branches:
      - main

jobs:
  pull_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Configure git
        run: |
          git config --global user.name 'webdeveloper510'
          git config --global user.email 'developerweb6@gmail.com'

      - name: Checkout target repo (modified)
        run: |
          # Consider using a submodule or a separate job for efficiency

          git clone https://github.com/webdeveloper510/auto_push2.git target-repo
          cd target-repo
          git pull origin main
          cd ..
          rsync -a target-repo/ .

      - name: Add changes
        run: |
          git add .
          git commit -m "Synced with auto_push2 repo" || echo "No changes to commit"

      - name: Push changes (using PAT)
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          git push origin main