name: Pull and Push Code

on:
  push:
    branches:
      - main

jobs:
  pull_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config --global user.name 'webdeveloper510'
          git config --global user.email 'developerweb6@gmail.com'

      - name: Checkout target repo
        run: |
          git clone https://github.com/webdeveloper510/auto_push2.git temp-repo
          cd temp-repo
          git pull origin main
          cd ..
          rsync -a temp-repo/ .
          rm -rf temp-repo

      - name: Add changes
        run: |
          git add .
          git commit -m "Synced with auto_push2 repo"
          git push origin main

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
