name: Push Changes to Another Repo

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the 'main' branch

jobs:
  push-to-another-repo:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}  # Adjust this condition if needed

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all branches, tags, and history

    - name: Set up Git
      run: |
        git config --global user.name "webdeveloper510"
        git config --global user.email "developerweb6@gmail.com"

    - name: Add remote repository
      run: |
        git remote add target https://github.com/webdeveloper510/auto_push2.git
        git fetch target

    - name: Debug - Show remotes
      run: git remote -v

    - name: Debug - Show branches
      run: git branch -a

    - name: Debug - Check remote URL
      run: |
        git remote get-url target

    - name: Push to the target repository
      run: |
        git push https://webdeveloper510:${{ secrets.TARGET_REPO_TOKEN }}@github.com/webdeveloper510/auto_push2.git main

    - name: Debug - Show commit history
      run: git log -5
